name: publish to nuget
on: [push]
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: setup dotnet core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.101

    - name: pack
      run: dotnet pack --configuration Release -o ./bin/publish

    - name: publish to github package
      run: dotnet nuget push bin/publish/*.nupkg --source https://nuget.pkg.github.com/gohopo/index.json -k ${{ secrets.GITHUB_TOKEN }}